name: 自动部署到服务器（FTP）
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取仓库代码
        uses: actions/checkout@v4

      - name: FTP部署到宝塔服务器
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: "114.215.181.118"
          username: "musicalbum"
          password: ${{ secrets.FTP_PASSWORD }}
          port: "21"
          protocol: ftp
          local-dir: "./"
          server-dir: "/www/wwwroot/musicalbum.chenpan.icu/"
          log-level: verbose
